apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-deployment
spec:
    revisionHistoryLimit: 1
    minReadySeconds: 5
    selector:
        matchLabels:
            app: {{ .Release.Name }}-pod
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-pod
        spec:
            containers:
                -   name: {{ .Release.Name }}-pod
                    image: {{ .Values.image }}
                    envFrom:
                        -   secretRef:
                                name: {{ .Release.Name }}-secrets
                        -   configMapRef:
                                name: {{ .Release.Name }}-configmap
                    ports:
                        -   containerPort: 3000
                    readinessProbe:
                        httpGet:
                            path: /
                            port: 3000
                            scheme: HTTP
                        periodSeconds: 10
                        successThreshold: 1
                        timeoutSeconds: 15
                        initialDelaySeconds: 60
            imagePullSecrets:
                -   name: {{ .Release.Name }}-registry-credentials
