apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |-
    {{ .Files.Get ".dockerconfigjson" | b64enc }}
