apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-secrets
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key | quote | indent 2 }}: {{ $value | b64enc | quote }}
  {{- end }}
