version: '3.7'
services:
  nextjs:
    build:
      context: ./next-starter
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./next-starter:/app
      - node_modules:/app/node_modules:cached
    env_file:
      - .env
    environment:
      - REACT_APP_PORT=3000
    ports:
      - "80:3000"

volumes:
  node_modules:
