apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-deployment
spec:
    revisionHistoryLimit: 1
    minReadySeconds: 5
    selector:
        matchLabels:
            app: {{ .Release.Name }}-pod
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-pod
        spec:
            containers:
                -   name: {{ .Release.Name }}-pod
                    image: postgres:10-alpine
                    envFrom:
                        -   secretRef:
                                name: {{ .Release.Name }}-secrets
                    volumeMounts:
                        -   name: storage
                            mountPath: /var/lib/mysql
                    ports:
                        -   containerPort: 5432
            volumes:
                -   name: storage
                    persistentVolumeClaim:
                        claimName: {{ .Release.Name }}-storage
