apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-storage
spec:
  accessModes:
    - ReadWriteOnce #ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
